---
kind: pipeline
type: docker
name: go-1-15

steps:
  - name: test
    image: golang:1.15
    commands:
      - make test

---
kind: pipeline
type: docker
name: go-1-14

steps:
  - name: test
    image: golang:1.14
    commands:
      - make test

---
kind: pipeline
type: docker
name: go-1-13

steps:
  - name: test
    image: golang:1.13
    commands:
      - make test
